"""Contains a dictionary mapping review keywords to their corresponding categories."""

CATEGORY_KEYWORDS = {
    "Food": [
        "taste",
        "food",
        "bland",
        "delicious",
        "cold",
        "undercooked",
        "burnt",
        "portion",
        "meal",
        "flavor",
        "spicy",
        "sweet",
        "salty",
        "fresh",
        "greasy",
        "soggy",
        "raw",
        "overcooked",
        "stale",
        "appetizer",
        "dessert",
        "entrée",
        "dish",
        "menu",
        "cuisine",
        "savory",
        "aroma",
        "presentation",
        "seasoning",
        "succulent",
        "mouthwatering",
        "overseasoned",
        "undercooked",
        "overcooked",
    ],
    "Service": [
        "rude",
        "service",
        "waiter",
        "staff",
        "apologize",
        "slow",
        "friendly",
        "manager",
        "helpful",
        "inattentive",
        "hostess",
        "bartender",
        "courteous",
        "impolite",
        "welcoming",
        "professional",
        "neglect",
        "attentive",
        "respectful",
        "service",
        "accommodating",
        "prompt",
        "unprofessional",
        "efficient",
        "knowledgeable",
        "unresponsive",
    ],
    "Environment": [
        "clean",
        "environment",
        "dirty",
        "music",
        "loud",
        "atmosphere",
        "decor",
        "lighting",
        "smell",
        "ambience",
        "crowded",
        "quiet",
        "comfortable",
        "cozy",
        "vibe",
        "aesthetic",
        "temperature",
        "seating",
        "noise",
        "layout",
        "romantic",
        "family-friendly",
        "intimate",
        "spacious",
        "cramped",
    ],
    "Price": [
        "expensive",
        "price",
        "cheap",
        "overpriced",
        "value",
        "deal",
        "worth",
        "affordable",
        "cost",
        "pricing",
        "reasonable",
        "steep",
        "discount",
        "bill",
        "charge",
        "fees",
        "special",
        "menu price",
        "budget",
        "pay",
        "wallet-friendly",
        "cost-effective",
        "premium",
        "economical",
    ],
    "Time": [
        "wait",
        "time",
        "long",
        "late",
        "slow",
        "timely",
        "fast",
        "quick",
        "delay",
        "on time",
        "prompt",
        "rush",
        "minutes",
        "hours",
        "speed",
        "duration",
        "efficient",
        "time-consuming",
        "lag",
        "reservation",
        "schedule",
        "punctual",
        "tardy",
    ],
    "Location": [
        "parking",
        "location",
        "convenient",
        "accessible",
        "downtown",
        "neighborhood",
        "view",
        "scenic",
        "nearby",
        "central",
        "remote",
        "walkable",
        "public transport",
        "commute",
        "landmark",
        "proximity",
        "hidden gem",
        "easy to find",
        "hard to find",
    ],
    "Drinks": [
        "cocktail",
        "drinks",
        "drink",
        "wine",
        "beer",
        "beverage",
        "drink menu",
        "bartender",
        "happy hour",
        "refreshing",
        "stale",
        "selection",
        "craft beer",
        "mocktail",
        "smoothie",
        "juice",
        "soda",
        "overpriced drinks",
        "watered down",
        "signature drink",
        "alcoholic",
        "non-alcoholic",
    ],
    "Cleanliness": [
        "spotless",
        "dirty",
        "hygienic",
        "sanitary",
        "filthy",
        "messy",
        "restroom",
        "table",
        "utensils",
        "napkins",
        "floor",
        "smell",
        "sticky",
        "tidy",
        "organized",
        "disinfected",
        "cleaned",
        "dirty dishes",
        "trash",
        "cluttered",
        "neat",
    ],
}
