name: Machine Learning Client CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Build & Test Machine Learning Client
    timeout-minutes: 5
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pipenv
      run: pip install pipenv

    - name: Install dependencies
      run: |
        cd machine-learning-client
        pipenv install --dev --deploy

    - name: Run tests with pytest
      run: |
        cd machine-learning-client
        pipenv run pytest --cov=helpers --cov-report=term
